version: '3.2'
services:

  revolutbot:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    command: revolutbot.py
    volumes:
      - .:/home/revolut/revolut-python
